---
  name: "Install all packages for FML stack"
    hosts: localhost
    tasks:
      name: "Install Python3"
      ansible.builtin.package:
      name:
        - mysql-server
        - python3
        - python3-pip
        - git
      ansible.builtin.pip:
      name: flask

