---
- name: Install all packages for FML stack
  hosts: localhost
  tasks:
          - name: Install Necessary Packages
            dnf:
                  name:
                          - mysql-server
                          - python3
                          - python3-pip
                          - git
                  state: latest
