---
- name: Setup Database
  hosts: localhost
  tasks:
    - name: Setup Database
      community.mysql.mysql_query:
        login_user: root
        login_password: whatever
        login_host: localhost
        login_port: 3306
        login_db: Cards
        query: SOURCE ../db.sql
